OUT_DIR      := out
LIB_VER      := $(shell go version)
VERSION_NAME := 0.1.0
CLI_TOOL     := staploy_cli

ARCHES := 386 amd64 arm arm64 riscv64 mipsle mips64le
.PHONY: buildAll clean_out createPkg $(ARCHES)
buildBinaries: $(ARCHES)
buildPkg: buildBinaries createPkg

$(ARCHES):
	GOOS=linux GOARCH=$@ go build -ldflags="-s -w -X staploy-worker/app/consts.VERSION=$(VERSION_NAME)" -o $(OUT_DIR)/$@/staploy staploy-worker

createPkg:
	$(CLI_TOOL) build \
		--i386 $(OUT_DIR)/386 --x86_64 $(OUT_DIR)/amd64 --arm $(OUT_DIR)/arm \
		--aarch64 $(OUT_DIR)/arm64 --riscv64 $(OUT_DIR)/riscv64 \
		--mipsel $(OUT_DIR)/mipsle --mips64el $(OUT_DIR)/mips64le \
		--app-name "staploy-worker" --executable "staploy" -o $(OUT_DIR) \
		--version-name "$(VERSION_NAME)" --lib-version "$(LIB_VER)"

clean_out:
	rm -rf $(OUT_DIR)