syntax = "proto3";
package com.staploy;

message BinaryInfo {
  string name = 1;
  string hash = 2;
}

message Version {
  string versionName = 1;
  repeated BinaryInfo entryBinaries = 2;
  optional string libVersion = 3;
}

message AppInfo {
  string appName = 1;
  optional string appDescription = 2;
}

message AppInfoFetch {
  AppInfo app = 1;
  repeated Version appVersion = 2;
}

message InstalledAppInfo {
  AppInfo app = 1;
  optional Version currentVersion = 2;
  repeated Version availableVersion = 3;
}